# 设置自然生成的精英怪是否会出现。注意：僵尸王等事件生物不属于自然生成的精英怪！若需禁用事件BOSS，需单独禁用事件。
doNaturalEliteMobSpawning: true
# 设置刷怪笼生成的生物是否会被转换为精英怪。不推荐启用！
doSpawnersSpawnEliteMobs: false
# 设置自然生成生物被转换为精英怪的概率
eliteMobsSpawnPercentage: 0.05
# 设置检测超级生物堆叠的扫描范围
superMobStackRange: 15
# 设置精英怪自然生成时的最高等级
# 注意：精英怪等级基于玩家穿戴的护甲和武器（仅护甲可提升至200级）
naturalEliteMobsLevelCap: 250
# 设置精英怪是否会根据等级穿戴护甲（仅视觉效果，不影响战斗）
doElitesWearArmor: true
# 设置精英怪是否会根据等级穿戴头盔（可防止白天自燃）
doElitesWearHelmets: true
# 设置精英怪是否显示粒子特效（向玩家警示其强度）
doNaturalEliteMobVisualEffects: true
# 设置刷怪笼生成的精英怪是否显示粒子特效
doSpawnerEliteMobVisualEffects: false
# 设置部分技能是否显示预警阶段特效（重要：预警通常代表技能可躲避，特效会提示躲避方向）
doPowerBuildupVisualEffects: true
# 设置玩家被精英怪击杀时是否显示定制死亡信息
doCustomEliteMobsDeathMessages: true
# 设置是否显示精英怪的血量指示器
doDisplayMobHealthOnHit: true
# 设置是否显示对精英怪造成的伤害数值
doDisplayMobDamageOnHit: true
# 设置是否根据距离出生点的距离提升精英怪等级
# 此值为基础等级的额外加成。例如：玩家在出生点附近穿戴100级装备，BOSS因距离获得+1级，最终生成101级
# 通常不推荐开启，尤其服务器存在随机传送系统时
doIncreaseEliteMobLevelBasedOnSpawnDistance: false
# 设置基于距离提升等级时，每段距离间隔的数值
distanceBetweenIncrements: 100.0
# 设置基于距离提升等级时，每个间隔提升的等级数
levelIncreaseAtIncrements: 1.0
# 设置是否隐藏精英怪技能效果直至进入战斗（出于性能考虑建议开启）
hideEliteMobPowersUntilAggro: true
# 设置对精英怪（非标准化伤害系统的区域副本BOSS）造成的伤害倍率。值越高BOSS越易击杀
# 2.0=200%伤害，0.5=50%伤害
damageToEliteMobMultiplierV2: 1.0
# 设置精英怪（非标准化伤害系统的区域副本BOSS）对玩家造成的伤害倍率。值越高BOSS伤害越高
# 2.0=200%伤害，0.5=50%伤害
damageToPlayerMultiplierV2: 1.0
# 设置是否允许追踪特殊BOSS
showCustomBossLocation: true
# 设置追踪BOSS位置时发送给玩家的消息
bossLocationMessage: '&7[EM] &2[点击追踪!]'
# 设置精英怪死亡时执行的命令。可用占位符：
# $level=BOSS等级，$name=BOSS名称
# $players=使命令对每个参与击杀的玩家执行。例如：若Bob和Steve击杀BOSS，'broadcast $players 击杀了BOSS!' 将分别广播两条消息
commandsOnEliteMobDeath: []
# 设置大型BOSS被击杀时发送给参与玩家的消息
bossKillParticipationMessage: '&e你的输出: &2$playerDamage'
# 设置BOSS脱离战斗后是否回满血（强烈推荐启用）
regenerateCustomBossHealthOnCombatEnd: true
# 设置追踪跨世界BOSS时发送的消息
defaultOtherWorldBossLocationMessage: '$name: 位于其他世界!'
# 设置玩家攻击BOSS弱点时伤害数值的前缀颜色
weakTextColor: '&9'
# 设置玩家攻击BOSS抗性时伤害数值的前缀颜色
resistTextColor: '&c'
# 设置玩家攻击BOSS弱点时显示的文本
weakText: '&9&l弱点!'
# 设置玩家攻击BOSS抗性时显示的文本
resistText: '&c&l抵抗!'
# 设置是否显示BOSS弱点攻击特效
doWeakEffect: true
# 设置是否显示BOSS抗性攻击特效
doResistEffect: true
# 设置对标准化伤害系统（区域副本BOSS）的伤害倍率。值越高BOSS越易击杀
# 2.0=200%伤害，0.5=50%伤害
damageToEliteMobMultiplier: 1.0
# 设置标准化伤害系统（区域副本BOSS）对玩家的伤害倍率。值越高BOSS伤害越高
# 2.0=200%伤害，0.5=50%伤害
damageToPlayerMultiplier: 1.0
# 设置使用标准化伤害的BOSS（通常为区域BOSS）的基础伤害
normalizedRegionalBossBaselineDamageV2: 3.0
# 设置使用标准化血量的BOSS（通常为区域BOSS）的基础生命值
normalizedRegionalBossBaselineHealthV3: 4.0
# 设置区域BOSS是否使用标准化战斗系统
# 强烈推荐启用，修改将导致预设内容失衡
normalizeRegionalBosses: true
# 设置BOSS脱离战斗回血时显示的消息
fullHealMessage: '&2满血恢复!'
# 设置BOSS抗性/弱点的伤害倍率
strengthAndWeaknessDamageMultipliers: 2.0
# 设置玩家抗性药效的伤害减免系数
resistanceDamageMultiplier: 1.0
# 设置玩家持盾时对近战攻击（不含技能）的伤害减免系数
blockingDamageReduction: 0.8